# Generated by Django 4.0.3 on 2022-06-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp_mobicall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
